
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Pay By Check Number') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" 
            title="<?php echo Mage::helper('core')->quoteEscape($this->__('Pay By Check Number')) ?>" 
            class="input-text required-entry"
            />
        </div>
    </li>
</ul>