    <div  hidden class="field">
        <label for="address_proof"><?php echo $this->__('Address Proof') ?></label>
        <div class="input-box">
            <input type="text" name="address_proof" title="<?php echo $this->quoteEscape($this->__('Address Proof')) ?>"
                id="address_proof" />
        </div>
    </div>
    <div class="field">
        <label for="address_proof_file"><?php echo $this->__('Address Proof') ?></label>
        <div class="input-box">
            <input type="file" onchange="uploadFile()" name="address_proof_file"
                title="<?php echo $this->quoteEscape($this->__('Address Proof')) ?>" id="address_proof_file" />
        </div>
    </div>
<script>
     function uploadFile() {
        var fileInput = document.getElementById('address_proof_file');
        var file = fileInput.files[0];
        var formData = new FormData();
        formData.append('address_proof', file);
        formData.append('form_key',FORM_KEY);
        fetch('<?php echo Mage::getUrl('*/sales_order_create/uploadFile'); ?>', {
            method: 'POST',
            body: formData,
        }).then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById('address_proof').value = data.path;
                } else {
                    alert('Upload failed: ' + data.error);
                }
            })
            .catch(error => {
                alert('Error uploading file.');
            });
    }
</script>